### ISSUE TITLE
diff supported OS with acceptance tests

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/vox-pupuli-tasks#216]
the metadata.json is the authoritative source of supported operating systems and their version for every puppet module. If a project has tests (any file in spec/acceptance/*.rb), we need to check if the tests are enabled for the correct operating systems.

Sadly beaker only supports a limited list of OSes for tests:
* Centos 6 / 7 / 8
* Debian 8 / 9 / 10
* Ubuntu 16.04 / 18.04 / 20.04

if those OSes are in metadata.json, the .sync.yml needs to list them, like this:

```yaml
---
.travis.yml:
  docker_sets:
    - set: ubuntu1604-64
    - set: centos7-64
    - set: debian8-64
```

besides that, the .travis.yml needs to contain an entry for each OS (.travis.yml is generated by modulesync based on .sync.yml)

```yaml
---
jobs:
  include:
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
    services: docker
```
